### ISSUE TITLE
Leiningen integration

### ISSUE THREAD

**Issue by Immortalin** [yoshiquest/forge-clj#8]
Is it possible to use leiningen instead of gradle?

**Comment by Immortalin** [comment]
Offtopic but you might want to take a look at [this](https://github.com/setupminimal/Cljsh)

**Comment by ryanhaney97** [comment]
Hmmm, this is interesting.
As for your original question, probably not as it is. Minecraft Forge uses Forge Gradle in order to do several processes such as deobfuscating and reobfuscating the code. As such, probably not unless you wish to rewrite forge gradle using leiningen.

However, that project you linked is... interesting. I'd like to see how well it works, and if it works well I just might be able to use forge-clj with it. I'll have to take a closer look at it though, particularly to see if it will even work in an obfuscated environment. I'll get to testing it this weekend.

**Comment by Immortalin** [comment]
The cljsh mod doesn't use AOT though so I think yours is still better for performance reasons

**Comment by ryanhaney97** [comment]
I think I'll stick with my current way of using this. It's a pain I know, but I'd like to get the api done first. I'll still keep this open, since I would like to do this.

I plan on adding a Leiningen (or maybe BOOT, haven't decided yet) task for forge-clj maybe far off in the future. However, since it would essentially involve rewriting the Forge Gradle plugin, whose code I don't really understand anyways, I don't plan on doing this anytime soon. If someone else wants to get a head start on this though, feel free to do so.

I leiningen TEMPLATE might not be out of the question though. I'll have to see what I can do.

**Comment by ryanhaney97** [comment]
Moved and respecified in Issue #28.
